apiVersion: v2
name: perses
description: Perses helm chart
icon: https://avatars.githubusercontent.com/u/77209215?s=200&v=4
type: application
version: 0.19.3
appVersion: "v0.52.0"
sources:
  - https://github.com/perses/perses
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/perses/helm-charts
    - name: Upstream Project
      url: https://github.com/perses/perses
keywords:
  - monitoring
  - metric
  - dashboarding
  - prometheus
